spring:
  application:
    name:
      demonew
  data:
    mongodb:
      host:
        localhost
      port:
        27017
      database:
        Journaldb
      auto-index-creation:
        true

server:
  port: 8081